{
  "exception_action": {
    "command": "ANSWER_TO_USER",
    "nodes": {
      "answer": [
        [
          "Произошёл технический сбой, извините. Давайте попробуем ещё раз?"
        ]
      ]
    }
  },
  "process_behavior_action": {
    "type": "process_behavior"
  },
  "before_action": {
    "type": "requirement",
    "action": {
		"type": "clear_all_scenarios"
	},
	"requirement": {
		"type": "template",
		"template": "{{ payload.new_session and settings['template_settings'].get('reset_context_on_new_session', False)}}"
	}
  },
  "smart_geo_success": {
    "type": "string",
    "command": "ANSWER_TO_USER",
    "nodes": {
      "pronounceText": "Геоданные пользователя",
      "items": [
        {
          "bubble": {
            "text": "Геоданные пользователя: {{ user.variables.smart_geo }}"
          }
        }
      ]
    }
  },
  "smart_geo_fail": {
    "type": "string",
    "command": "ANSWER_TO_USER",
    "nodes": {
      "pronounceText": "Ошибка при получении геоданных пользователя",
      "items": [
        {
          "bubble": {
            "text": "Ошибка при получении геоданных пользователя"
          }
        }
      ]
    }
  }
}